version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./templates:/templates
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: web_block
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 04041954-
    ports:
      - 5432:5432
