version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:8080"
    volumes:
      - ./templates:/templates
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: "${NAME_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${PASSWORD_DB}"
    ports:
      - ${PORT_DB}:5432
    env_file:
          - .env
